package com.construction.domain;

import static com.construction.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class BuildingProjectAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBuildingProjectAllPropertiesEquals(BuildingProject expected, BuildingProject actual) {
        assertBuildingProjectAutoGeneratedPropertiesEquals(expected, actual);
        assertBuildingProjectAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBuildingProjectAllUpdatablePropertiesEquals(BuildingProject expected, BuildingProject actual) {
        assertBuildingProjectUpdatableFieldsEquals(expected, actual);
        assertBuildingProjectUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBuildingProjectAutoGeneratedPropertiesEquals(BuildingProject expected, BuildingProject actual) {
        assertThat(expected)
            .as("Verify BuildingProject auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBuildingProjectUpdatableFieldsEquals(BuildingProject expected, BuildingProject actual) {
        assertThat(expected)
            .as("Verify BuildingProject relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getType()).as("check type").isEqualTo(actual.getType()))
            .satisfies(e -> assertThat(e.getAddress()).as("check address").isEqualTo(actual.getAddress()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(
                e -> assertThat(e.getMinPrice()).as("check minPrice").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getMinPrice())
            )
            .satisfies(e -> assertThat(e.getCompletionDate()).as("check completionDate").isEqualTo(actual.getCompletionDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBuildingProjectUpdatableRelationshipsEquals(BuildingProject expected, BuildingProject actual) {}
}
